[server]
host = "0.0.0.0"
port = 8080
environment = "prod"

[database]
max_connections = 50
min_connections = 5
connect_timeout = 10

[logging]
level = "warn"
file_enabled = true
file_path = "logs/production.log"
json_format = true

[auth]
jwt_expiration = 28800  # 8 hours
bcrypt_cost = 14
