name: Send Results to Discord

on:
  workflow_run:
    workflows: ["Run Docker Container"]
    types:
      - completed

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI & jq
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git

      - name: Download output artifact using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download --name output --dir output

      - name: Read and format output
        run: |
          FORMATTED_OUTPUT="**Work Distribution Results** 📊\n\n"

          FORMATTED_OUTPUT+="🛢️ **Tanks**:\n➜ $(jq -r '.Tanks | join(", ")' output/output.txt)\n\n"
          FORMATTED_OUTPUT+="🗑️ **Bin**:\n➜ $(jq -r '.Bin | join(", ")' output/output.txt)\n\n"
          FORMATTED_OUTPUT+="🚪 **Front**:\n➜ $(jq -r '.Front | join(", ")' output/output.txt)\n\n"
          FORMATTED_OUTPUT+="🚻 **Toilet A**:\n➜ $(jq -r '.["Toilet A"] | join(", ")' output/output.txt)\n\n"
          FORMATTED_OUTPUT+="🚻 **Toilet B**:\n➜ $(jq -r '.["Toilet B"] | join(", ")' output/output.txt)\n\n"
          FORMATTED_OUTPUT+="🏡 **Backyard**:\n➜ $(jq -r '.Backyard | join(", ")' output/output.txt)\n\n"
          FORMATTED_OUTPUT+="🛋️ **Parlor**:\n➜ $(jq -r '.Parlor | join(", ")' output/output.txt)\n\n"

          echo "{\"content\": \"$FORMATTED_OUTPUT\"}" > discord_payload.json

      - name: Send to Discord using curl
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d @discord_payload.json \
            ${{ secrets.DISCORD_WEBHOOK }}
