name: Send Results to Discord

on:
  workflow_run:
    workflows: ["Run Docker Container"]
    types:
      - completed

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download output artifact using GitHub CLI
        run: |
          gh run download --artifact output --dir output

      - name: Read output file
        id: read-output
        run: |
          OUTPUT=$(cat output/output.txt)  # Read the content of the output.txt file
          echo "OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV  # Set the content as an environment variable
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Discord using curl
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"${{ env.OUTPUT }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
