name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 */14 * *'  # Runs every 14 days

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/work-group-generator:latest .

      - name: Run Docker Container and Collect Output
        id: run_container
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/work-group-generator:latest > output.txt
          cat output.txt || echo "⚠️ No output.txt file found!"

      - name: Set Workflow Output (Base64 Encoding Fix)
        id: set_output
        run: |
          if [ -s output.txt ]; then
            WORK_OUTPUT=$(base64 -w0 output.txt)
            echo "WORK_OUTPUT=$WORK_OUTPUT" >> $GITHUB_ENV
          else
            echo "❌ Error: No output generated!" >&2
            exit 1
          fi

  send-to-discord:
    needs: build-and-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode Output for Discord
        run: |
          if [ -z "${{ env.WORK_OUTPUT }}" ]; then
            echo "❌ No output found! Skipping Discord notification."
            exit 1
          fi

          # Decode base64-encoded output to file
          echo "${{ env.WORK_OUTPUT }}" | base64 -d > formatted_output.txt
          ls -lah formatted_output.txt  # Debugging step to verify file exists
          cat formatted_output.txt || echo "⚠️ No content in formatted_output.txt"

      - name: Format Output for Discord
        run: |
          FORMATTED_OUTPUT="📊 **Work Distribution Results**\n\n"

          while IFS= read -r line; do
            key=$(echo "$line" | awk -F': ' '{print $1}')
            value=$(echo "$line" | awk -F': ' '{print $2}' | tr -d '[]"')

            case "$key" in
              "Tank") icon="🛢️"; sub_icon="💧";;
              "Bin") icon="🗑️"; sub_icon="🚮";;
              "Frontyard") icon="🚪"; sub_icon="🛠️";;
              "Toilet A") icon="🚻"; sub_icon="🧽";;
              "Toilet B") icon="🚻"; sub_icon="🧼";;
              "Backyard") icon="🏡"; sub_icon="🌿";;
              "Parlor") icon="🛋️"; sub_icon="🧹";;
              *) icon="🔹"; sub_icon="";;
            esac

            FORMATTED_OUTPUT+="$icon **$key**\n$sub_icon Assigned: $value\n\n"
          done < formatted_output.txt

          echo "{\"content\": \"$FORMATTED_OUTPUT\"}" > discord_payload.json

      - name: Debug Discord Payload
        run: cat discord_payload.json

      - name: Send to Discord
        run: |
          if [ -s discord_payload.json ]; then
            curl -X POST -H "Content-Type: application/json" \
              --fail --silent --show-error \
              -d @discord_payload.json \
              ${{ secrets.DISCORD_WEBHOOK }}
          else
            echo "⚠️ No data to send to Discord."
          fi
