name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 */14 * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4

  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

  
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/work-group-generator:latest .

  
      - name: Run Docker Container and collect output
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/work-group-generator:latest > output.txt

  
      - name: Validate output
        run: |
          if [ ! -f output.txt ]; then
            echo "Error: output.txt is missing!"
            exit 1
          fi
          cat output.txt

  
      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: work-distribution-output
          path: output.t