name: Run Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 */14 * *'  # Runs every two weeks

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --progress=plain -t ghcr.io/${{ github.repository }}/my-image:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}/my-image:${{ github.sha }} ghcr.io/${{ github.repository }}/my-image:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-image:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/my-image:latest

      - name: Run Docker Container and Capture Output
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/my-image:${{ github.sha }} | tee output.txt
          sleep 2  # Ensure file system sync before checking output file

      - name: Debug Files in Workspace
        run: ls -lah

      - name: Validate Output
        run: |
          if [ ! -s output.txt ]; then
            echo "Error: output.txt is missing or empty!"
            exit 1
          fi
          cat output.txt

      - name: Upload Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.txt
