name: Distribute Work and Notify Discord

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Runs at 10:00 UTC on the 4th and 20th of every month.
    - cron: '0 10 4,20 * *'

jobs:
  build-run-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Work Distributor and Format Output
        id: work_distributor
        run: |
          output=$(cargo run)
          # --- THIS IS THE CRITICAL FIX FOR FORMATTING ---
          # Escape special characters so the output can be safely injected into a JSON string.
          escaped_output="${output//'%'/'%25'}"
          escaped_output="${escaped_output//$'\n'/'\n'}"
          escaped_output="${escaped_output//$'\r'/'\r'}"
          echo "DISTRIBUTION_OUTPUT=${escaped_output}" >> $GITHUB_OUTPUT

      - name: Send notification to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          # The 'embeds' format provides clean, professional output and now works with the escaped output.
          embeds: |
            [{
              "title": "📊 Work Distribution Results",
              "description": "Hello everyone! Here is the new work distribution for the next two weeks.\n\n${{ steps.work_distributor.outputs.DISTRIBUTION_OUTPUT }}",
              "color": "3447003"
            }]

      - name: Commit updated assignment history
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions@github.com'
          git add long_term_history.json
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update assignment history for new cycle"
            git push
          else
            echo "No changes to assignment history to commit."
          fi