name: Distribute Work and Notify Discord

on:
  # Allows manual triggering for the first run and for any future emergencies.
  workflow_dispatch:
  
  # Runs checks on pull requests to ensure code quality.
  pull_request:
    branches:
      - main
      
  # The primary trigger after the first manual run.
  push:
    branches:
      - main
      
  # --- The Final, Correct Schedule ---
  schedule:
    # Runs at 10:00 UTC on the 4th and 20th day of every month.
    # This creates a perfect "every two weeks" cycle starting from today, the 20th.
    - cron: '0 10 4,20 * *'

jobs:
  build-run-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Work Distributor
        id: work_distributor
        run: |
          output=$(cargo run)
          # This is the correct and robust way to handle multi-line output.
          echo "DISTRIBUTION_OUTPUT<<EOF" >> $GITHUB_OUTPUT
          echo "${output}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send notification to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          # The simple 'message' parameter is the most reliable way to send the output.
          message: |
            Hello everyone! Here is the new work distribution for the next two weeks.
            ${{ steps.work_distributor.outputs.DISTRIBUTION_OUTPUT }}

      - name: Commit updated assignment history
        # This step will correctly run on pushes, scheduled runs, or manual runs, but not on PRs.
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions@github.com'
          git add long_term_history.json
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update assignment history for new cycle"
            git push
          else
            echo "No changes to assignment history to commit."
          fi