name: Distribute Work and Notify Discord

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-run-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Work Distributor
        id: work_distributor
        run: |
          output=$(cargo run)
          echo "DISTRIBUTION_OUTPUT<<EOF" >> $GITHUB_OUTPUT
          echo "${output}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send notification to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          embeds: |
            [{
              "title": "📊 Work Distribution Results",
              "description": "${{ steps.work_distributor.outputs.DISTRIBUTION_OUTPUT }}",
              "color": "3447003"
            }]

      # --- THIS STEP NOW ONLY RUNS ON THE MAIN BRANCH ---
      - name: Commit updated assignment history
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions@github.com'
          git add long_term_history.json
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update assignment history for new cycle"
            git push
          else
            echo "No changes to assignment history to commit."
          fi

      # --- THIS STEP NOW ONLY RUNS ON THE MAIN BRANCH ---
      - name: Schedule the Next Run
        if: github.ref == 'refs/heads/main'
        uses: gr2m/invoke-workflow-run-action@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          workflow: ${{ github.workflow }}
          delay_seconds: 1209600 # 14 days
          token: ${{ secrets.GITHUB_TOKEN }}